#!/bin/bash

echo "========================================"
echo "  PX4 Offboard 시뮬레이션 실행 가이드"
echo "========================================"
echo ""
echo "3개의 터미널이 필요합니다:"
echo ""
echo "[터미널 1] PX4 SITL 실행:"
echo "  cd ~/PX4-Autopilot"
echo "  make px4_sitl gz_x500"
echo ""
echo "[터미널 2] Micro XRCE-DDS Agent 실행:"
echo "  /usr/local/microxrcedds_agent-3.0.1/bin/MicroXRCEAgent udp4 -p 8888"
echo ""
echo "[터미널 3] Offboard 예제 실행:"
echo "  cd ~/offboard_ws"
echo "  source /opt/ros/humble/setup.bash"
echo "  source ~/px4_ros2_ws/install/setup.bash"
echo "  source install/setup.bash"
echo "  ros2 run offboard_example offboard_control"
echo ""
echo "========================================"
